### PR TITLE
Repair/update the builds

### PR DESCRIPTION
**Pull request by 4c0n**
Fixed the builds, the are now 2 jobs per PHP (latest dependencies and oldest dependencies) version and the supported versions are 7.2, 7.3 and 7.4

### CODE REVIEW

**Comment by 4c0n** [comment]
@pamil The build is updated and fixed, could you take a look please?

If/when you merge this, could you please use the squash strategy? I'd hate to see this whole commit stream in the main branch. :)

**Comment by 4c0n** [comment]
@pamil https://www.youtube.com/watch?v=1U888OuzC6w

**Comment by 4c0n** [comment]
@pamil Any specific reason you're not responding? You asked me to do this, so please have a look at it.

**Comment by 4c0n** [comment]
@pamil When do you think you'll have time to deal with this?

**Comment by lchrusciel** [comment]
Hey Youri,

Sorry for the long feedback loop. We had internally a few commitments to finish, which blocked us from being active on our additional repositories. I hope we will find more time for it after Sylius 1.8 will be released (14th of September). 

However, in terms of this PR, I'm totally in favor of merging it 👍

**Review by lchrusciel — APPROVED** [review]

**Comment by 4c0n** [comment]
Hi Lukasz,

Thanks for the review! Nothing special going on here logic wise, just bringing everything to 2020.
Hope everything is going well with the Sylius development. Lots of big changes!

**Review by pamil — APPROVED** [review]

**Comment by pamil** [comment]
Thanks, Youri! :1st_place_medal:

**Pull request merged**
